describe('Patient Register', () => {
  it('It registers user and patient info', () => {
    cy.visit('/')
    cy.contains('Sign Up').click()
    //KO    
    cy.get('[name="email"]').type('harry')   
    cy.get('[name="form"]').submit()
    cy.contains('Email must be a valid email address')
    cy.contains('Password is required')
    //OK
    cy.get('[name="email"]').type('harry@windsor.uk')   
    cy.get('[name="password"]').type('password')  
    cy.get('[name="form"]').submit()
    cy.url().should('include', '/login')
    cy.login('harry@windsor.uk', 'password')
    cy.get('[name="firstName"]').type('harry')
    cy.get('[name="lastName"]').type('windsor')    
    cy.get('[name="nhsNumber"]').type('ZZ 767899 T')
    cy.get('[name="birthdate"]').type('1971-02-21')
    cy.get('[name="phone"]').type('020 7287 7323')
    cy.get('[name="address"]').type('41 Carnaby St')
    cy.get('[name="postCode"]').type('W1V 1PD')
    cy.get('[name="city"]').type('London')       
    cy.get('[name="form"]').submit()
    cy.contains('harry')
    cy.contains('windsor')    
    cy.contains('ZZ 767899 T')
    cy.contains('1971-02-21')
    cy.contains('020 7287 7323')
    cy.contains('41 Carnaby St')
    cy.contains('W1V 1PD')
    cy.contains('London')  
  })
})