name: angular ci - app
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'app/'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test-headless
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=ella-dee
            -Dsonar.projectKey=ella-dee_app
            -Dsonar.sources=app/src
            -Dsonar.tests=app/src
            -Dsonar.typescript.lcov.reportPaths=app/coverage/lcov-report/lcov.info
            -Dsonar.exclusions=node_modules/**,assets/**
            -Dsonar.coverage.exclusions=*.spec.ts
            -Dsonar.test.inclusions=*.spec.ts
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
