name: Java CI/CD for frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'app'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test-headless
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@main
        with:
          args: >
            -Dsonar.organization=ella-dee
            -Dsonar.projectKey=ella-dee_app
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.typescript.lcov.reportPaths=coverage/app/lcov-report/lcov.info
            -Dsonar.exclusions=node_modules/**,assets/**,*.spec.ts
            -Dsonar.test.inclusions=*.spec.ts
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
