name: Java CI - ms-users

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'api/ms-users'
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Compile with Maven
        run: mvn clean compile

      - name: Run Test With Maven
        run: mvn clean test

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USERS }}
        run: mvn verify sonar:sonar -Dsonar.projectKey=ella-dee_ms-users

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ms-users
          path: ./api/ms-users/target/ms-users-0.0.1-SNAPSHOT.jar